### ISSUE TITLE
Refs should be restricted to just non-pattern LHS expressions.

### ISSUE THREAD

**Issue by isiahmeadows** [rbuckton/proposal-refs#2]
It seems pointless to create a reference you never retain. Also, in the spec, there is no way to create references to already-evaluated values. References are only used for reading LHS items, for things like `typeof` and whether to add a descriptor to an object.

Also, if you wish to mutate a result that isn't merely a reference, it's easy enough to just define `let foo = bar` and mutate `foo` directly.

**Comment by rbuckton** [comment]
I originally had this restriction, but a few months ago a similar proposal was brought up on es-discuss that **only** supported patterns. I thought it was worthwhile to consider the features together.

The goal of `let ref foo = ref bar` is that mutating `foo` mutates `bar`. Consider the following example in the explainer:

```js
function max(ref first, ref second, ref third) {
  const ref max = first > second ? ref first : ref second;
  return max > third ? ref max : ref third;
}

let x = 1, y = 2, z = 3;
let ref w = max(ref x, ref y, ref z);
w = 4; // (a)
print(x); // 1
print(y); // 2
print(z); // 4 (b)
```

Here `w` is effectively the same binding as `z`. Mutating `w` (at (a) above) mutates `z` (which can be seen at (b) above).

**Comment by rbuckton** [comment]
Also, the rationale for using `value` vs `set()` and `deref()` (from your example in the es-discuss thread) is so that References can be the target of an assignment pattern, i.e.:

```js
let x = 0;
let y = ref x;
[y.value] = [1];
print(x); // 1
```

If you use methods to set/get then you cannot use references in assignment patterns. This is very useful for refactoring scenarios (which we've run into in TypeScript and VS Code and is one of the reasons I put together this strawman in the first place).

**Comment by isiahmeadows** [comment]
I get that (and I wasn't strongly tied to the method).

However, your `max` isn't a counterexample to mine. All `ref` operands are themselves LHS expressions. A RHS expression that satisfies your grammar would be like `ref !a` or `ref -foo(1, 2, 3)`, of which the former doesn't make much sense to me and the latter is ambiguous with subtraction.

**Comment by rbuckton** [comment]
Ah, I understand what you are saying now. I hadn't spent a lot of time on the formal grammar since I originally put together the strawman. I'll update the explainer.

**Comment by isiahmeadows** [comment]
Overall, this is mostly what I had in mind myself, so great work, BTW!
