### ISSUE TITLE
Vue3 use case

### ISSUE THREAD

**Issue by hax** [rbuckton/proposal-refs#7]
As upcoming Vue 3, there is `ref` API.

```js
import { ref, watchEffect } from 'vue'

const count = ref(0)

function increment() {
  count.value++
}

const renderContext = {
  count,
  increment
}

watchEffect(() => {
  renderTemplate(
    `<button @click="increment">{{ count }}</button>`,
    renderContext
  )
})
```

`ref(0)` is basically `reactive({value: 0})`

So maybe ref expression could be extended to support literal, aka. `ref 0` desugar to `ref {value: 0}.value`.

Then the previous example could be rewritten to

```js
import { reactive, watchEffect } from 'vue'

let ref count = reactive(ref 0)

function increment() {
  count++
}

const renderContext = {
  count: ref count,  // note this line
  increment
}

watchEffect(() => {
  renderTemplate(
    `<button @click="increment">{{ count }}</button>`,
    renderContext
  )
})
```

The original `{count}` need to be changed to `{count: ref count}` which seems not satisfying. Not sure whether we could have some shorthand syntax like `{ ref count }` or even just `{count}`.

**Comment by rbuckton** [comment]
I'm not sure I'd support that kind of shorthand as it is too esoteric. It would be trivial to write something reusable like this:

```js
function counter() { return { value: 0 } };
let ref count = reactive(ref counter().value);
```
or just
```js
function newCounter() {
  let value = 0;
  return ref value;
}
let ref count = reactive(newCounter());
```
